-- Major countries
INSERT INTO countries (id, name, iso_code) VALUES
(1, 'United States', 'US'),
(2, 'Canada', 'CA'),
(3, 'United Kingdom', 'GB'),
(4, 'Australia', 'AU'),
(5, 'India', 'IN'),
(6, 'Germany', 'DE'),
(7, 'France', 'FR'),
(8, 'China', 'CN'),
(9, 'Japan', 'JP'),
(10, 'Brazil', 'BR'),
(11, 'Pakistan', 'PK'),
(12, 'South Africa', 'ZA'),
(13, 'Mexico', 'MX'),
(14, 'Italy', 'IT'),
(15, 'Russia', 'RU');

-- Major states/provinces (sample, not exhaustive)
INSERT INTO states (id, country_id, name) VALUES
(1, 1, 'California'),
(2, 1, 'Texas'),
(3, 1, 'New York'),
(4, 2, 'Ontario'),
(5, 2, 'Quebec'),
(6, 3, 'England'),
(7, 3, 'Scotland'),
(8, 4, 'New South Wales'),
(9, 4, 'Victoria'),
(10, 5, 'Maharashtra'),
(11, 5, 'Delhi'),
(12, 6, 'Bavaria'),
(13, 7, 'Île-de-France'),
(14, 8, 'Guangdong'),
(15, 9, 'Tokyo'),
(16, 10, 'São Paulo'),
(17, 11, 'Punjab'),
(18, 12, 'Gauteng'),
(19, 13, 'Jalisco'),
(20, 14, 'Lombardy'),
(21, 15, 'Moscow');

-- Major cities (sample, not exhaustive)
INSERT INTO cities (id, state_id, name) VALUES
(1, 1, 'Los Angeles'),
(2, 1, 'San Francisco'),
(3, 2, 'Houston'),
(4, 3, 'New York City'),
(5, 4, 'Toronto'),
(6, 5, 'Montreal'),
(7, 6, 'London'),
(8, 7, 'Edinburgh'),
(9, 8, 'Sydney'),
(10, 9, 'Melbourne'),
(11, 10, 'Mumbai'),
(12, 11, 'Delhi'),
(13, 12, 'Munich'),
(14, 13, 'Paris'),
(15, 14, 'Guangzhou'),
(16, 15, 'Tokyo'),
(17, 16, 'São Paulo'),
(18, 17, 'Lahore'),
(19, 18, 'Johannesburg'),
(20, 19, 'Guadalajara'),
(21, 20, 'Milan'),
(22, 21, 'Moscow');
